/*
 * GitHub https://github.com/JetsadaWijit/CS318-Project-Revenue-Expeness.git
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.project.project;
import java.io.BufferedReader;
import java.io.BufferedWriter;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.IOException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFileChooser;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;
/**
 *
 * @author Ze_ro
 */
public class MenuUI extends javax.swing.JFrame {
    
    ArrayList<String> revenuename = new ArrayList<>();
    ArrayList<Double> revenueamount = new ArrayList<>();
    ArrayList<String> revenuememo = new ArrayList<>();
    ArrayList<String> expenessname = new ArrayList<>();
    ArrayList<Double> expenessamount = new ArrayList<>();
    ArrayList<String> expenessmemo = new ArrayList<>();
    
    showdata shd = new showdata();
    
    /**
     * Creates new form MenuUI
     */
    public MenuUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btngroupRE = new javax.swing.ButtonGroup();
        btngroupcal = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jrdrevenue = new javax.swing.JRadioButton();
        jrdexpeness = new javax.swing.JRadioButton();
        jtfname = new javax.swing.JTextField();
        jtfamount = new javax.swing.JTextField();
        jtfmemo = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jbtnadd = new javax.swing.JButton();
        jbtnclear = new javax.swing.JButton();
        jbtncalculate = new javax.swing.JButton();
        jlbal = new javax.swing.JLabel();
        jbtnsavefile = new javax.swing.JButton();
        jbtncleartable = new javax.swing.JButton();
        jlresult = new javax.swing.JLabel();
        jtffilename = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jbtnimportfile = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jrdrvep = new javax.swing.JRadioButton();
        jrdrv = new javax.swing.JRadioButton();
        jrdep = new javax.swing.JRadioButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Name");

        jLabel2.setText("Amount");

        jLabel3.setText("Memo");

        btngroupRE.add(jrdrevenue);
        jrdrevenue.setText("Revenue");

        btngroupRE.add(jrdexpeness);
        jrdexpeness.setText("Expeness");

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Name", "Amount", "Memo", "Type"
            }
        ));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        jbtnadd.setText("Add");
        jbtnadd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnaddActionPerformed(evt);
            }
        });

        jbtnclear.setText("Clear");
        jbtnclear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnclearActionPerformed(evt);
            }
        });

        jbtncalculate.setText("Calculate");
        jbtncalculate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtncalculateActionPerformed(evt);
            }
        });

        jlbal.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlbal.setText("Balance");

        jbtnsavefile.setText("Save to file");
        jbtnsavefile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnsavefileActionPerformed(evt);
            }
        });

        jbtncleartable.setText("Clear Table");
        jbtncleartable.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtncleartableActionPerformed(evt);
            }
        });

        jlresult.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlresult.setText("Result");

        jtffilename.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("File name");

        jbtnimportfile.setText("Import File");
        jbtnimportfile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnimportfileActionPerformed(evt);
            }
        });

        jButton1.setText("Exit");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        btngroupcal.add(jrdrvep);
        jrdrvep.setText("Revenue&Expeness");

        btngroupcal.add(jrdrv);
        jrdrv.setText("Revenue");

        btngroupcal.add(jrdep);
        jrdep.setText("Expeness");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jtfmemo, javax.swing.GroupLayout.DEFAULT_SIZE, 111, Short.MAX_VALUE)
                            .addComponent(jtfamount)
                            .addComponent(jtfname)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jbtnadd, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 1, Short.MAX_VALUE)
                            .addComponent(jrdrevenue, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 71, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jrdexpeness)
                            .addComponent(jbtnclear, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(54, 54, 54)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jrdrvep, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jrdrv, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jrdep, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(jlresult, javax.swing.GroupLayout.PREFERRED_SIZE, 238, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 77, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(61, 61, 61)
                                .addComponent(jbtncalculate)
                                .addGap(18, 18, 18)
                                .addComponent(jlbal, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 375, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jtffilename)
                    .addComponent(jbtnsavefile, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jbtncleartable, javax.swing.GroupLayout.DEFAULT_SIZE, 96, Short.MAX_VALUE)
                    .addComponent(jbtnimportfile, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(96, 96, 96)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(jtfname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(jtfamount, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jtfmemo, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jrdrevenue)
                            .addComponent(jrdexpeness))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jbtnadd)
                            .addComponent(jbtnclear)))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jbtnimportfile)
                            .addGap(46, 46, 46)
                            .addComponent(jLabel4)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(jtffilename, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jbtnsavefile)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jbtncleartable))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jrdrvep)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jbtncalculate)
                            .addComponent(jlbal))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jrdrv)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton1)
                        .addGap(20, 20, 20))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jrdep)
                            .addComponent(jlresult))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbtnaddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnaddActionPerformed
        String namein = jtfname.getText();
        String amountin = jtfamount.getText();
        String memoin = jtfmemo.getText();
        
        if (namein.equals("")){
            JOptionPane.showMessageDialog(null, "Please Input Name");
            jlresult.setText("Name must not be null");
        } else if (amountin.equals("")){
            JOptionPane.showMessageDialog(null, "Please Input Amount");
            jlresult.setText("Amount must not be null");
        } else if (memoin.equals("")){
            JOptionPane.showMessageDialog(null, "Please Input Memo");
            jlresult.setText("Memo must not be null");
        } else {
        
            double amount = Double.parseDouble(amountin);
        
            if (jtfname == null){
                JOptionPane.showMessageDialog(null, "Please Write name");
            }
        
            if (jrdrevenue.isSelected()){
                revenuename.add(namein);
                revenueamount.add(amount);
                revenuememo.add(memoin);
                String type = "revenue";
            
                String[] data = {namein,Double.toString(amount),memoin,type};
                DefaultTableModel tblModel = (DefaultTableModel)jTable1.getModel();
                tblModel.addRow(data);

            } else if (jrdexpeness.isSelected()) {
                expenessname.add(namein);
                expenessamount.add(amount);
                expenessmemo.add(memoin);
                String type = "expeness";
            
                String[] data = {namein,Double.toString(amount),memoin,type};
                DefaultTableModel tblModel = (DefaultTableModel)jTable1.getModel();
                tblModel.addRow(data);
            } else {
                JOptionPane.showMessageDialog(null, "Please Select Revenue or Expenness radio button");
            }
            jlresult.setText("Add to table success");
        }
    }//GEN-LAST:event_jbtnaddActionPerformed

    private void jbtnclearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnclearActionPerformed
        jtfname.setText("");
        jtfamount.setText("");
        jtfmemo.setText("");
        jlresult.setText("Clear Successful");
    }//GEN-LAST:event_jbtnclearActionPerformed

    private void jbtncalculateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtncalculateActionPerformed
        if (jrdrvep.isSelected()){
            double sumrv = 0;
            for (double numrv : revenueamount){
                sumrv += numrv;
            }
            double sumep = 0;
            for (double numep : expenessamount){
                sumep += numep;
            }
            double sum = sumrv - sumep;
            //System.out.println(sum);
            jlbal.setText(Double.toString(sum) + " Bath");
            jlresult.setText("Caculate complete");
        } else if (jrdrv.isSelected()) {
            double sumrv = 0;
            for (double numrv : revenueamount){
                sumrv += numrv;
            }
            jlbal.setText(Double.toString(sumrv) + " Bath");
            jlresult.setText("Caculate complete");
        } else if (jrdep.isSelected()) {
            double sumep = 0;
            for (double numep : expenessamount){
                sumep += numep;
            }
            jlbal.setText(Double.toString(sumep) + " Bath");
            jlresult.setText("Caculate complete");
        } else {
            JOptionPane.showMessageDialog(null, "Please Select value to caculate");
            jlresult.setText("User have to select type of caculate");
        }
    }//GEN-LAST:event_jbtncalculateActionPerformed

    private void jbtnsavefileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnsavefileActionPerformed
        FileWriter fileWriter;
        File f = new File("C:\\project");
        if (f.mkdir() == true) {
            System.out.println("Directory has been created successfully");
        } else {
            System.out.println("Directory cannot be created");
        }
        String filename = jtffilename.getText();
        if (filename.equals("")){
            JOptionPane.showMessageDialog(null, "Please Input Name to generate file");
            jlresult.setText("File name must not be null");
        } else {
            /*
            int szrv = revenueamount.size();
            int szep = expenessamount.size();
            try {
                fileWriter = new FileWriter("C:/project/" + filename + ".bin");
                fileWriter.write("Revenue:" + "\n");
                for (int i = 0; i < szrv; i++){
                    fileWriter.write("=========" + "\n");
                    fileWriter.write("ID    " + " : " + i + "\n");
                    fileWriter.write("Name  " +" : " + revenuename.get(i) + "\n");
                    fileWriter.write("Amount" +" : " + revenueamount.get(i) + "\n");
                    fileWriter.write("Memo  " +" : " + revenuememo.get(i) + "\n");
                }
                fileWriter.write("==================================" + "\n");
                fileWriter.write("expeness:" + "\n");
                for (int i = 0; i < szep; i++){
                    fileWriter.write("=========" + "\n");
                    fileWriter.write("ID    " + " : " + i + "\n");
                    fileWriter.write("Name  " +" : " + expenessname.get(i) + "\n");
                    fileWriter.write("Amount" +" : " + expenessamount.get(i) + "\n");
                    fileWriter.write("Memo  " +" : " + expenessmemo.get(i) + "\n");
                }
                double sumrv = 0;
                for (double numrv : revenueamount){
                    sumrv += numrv;
                }
                double sumep = 0;
                for (double numep : expenessamount){
                    sumep += numep;
                }
                double sum = sumrv - sumep;
            
                fileWriter.write("==================================" + "\n");
                fileWriter.write("Revenue " + " : " + sumrv + "\n");
                fileWriter.write("expeness" + " : " + sumep + "\n");
                fileWriter.write("Balance " + " : " + sum + "\n");
                fileWriter.close();
                jlresult.setText("File is saved");
            } catch (IOException ex) {
                Logger.getLogger(MenuUI.class.getName()).log(Level.SEVERE, null, ex);
            }*/
            
            String filePath = "C:\\project\\" + filename + ".bin";
            File file = new File(filePath);
            try {
                FileWriter fw = new FileWriter(file);
                BufferedWriter bw = new BufferedWriter(fw);
                
                for (int i = 0; i <jTable1.getRowCount(); i++){
                    for (int j = 0; j < jTable1.getColumnCount();j++){
                        bw.write(jTable1.getValueAt(i, j).toString() + " ");
                    }
                    bw.newLine();
                }
                
                bw.close();
                fw.close();
                jlresult.setText("File is saved");
            } catch (IOException ex) {
                Logger.getLogger(MenuUI.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_jbtnsavefileActionPerformed

    private void jbtncleartableActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtncleartableActionPerformed
        jTable1.setModel(new DefaultTableModel(null, new String[] {"Name","Amount","Memo","Type"}));
        revenuename.clear();
        revenueamount.clear();
        revenuememo.clear();
        expenessname.clear();
        expenessamount.clear();
        expenessmemo.clear();
        jtffilename.setText("");
        jlbal.setText("Balance");
        jlresult.setText("Table and Data are deleted");
    }//GEN-LAST:event_jbtncleartableActionPerformed

    private void jbtnimportfileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnimportfileActionPerformed
        // File for manual select file to import ( Learning from youtube )
        JFileChooser fileChooser = new JFileChooser();
        int response = fileChooser.showOpenDialog(null);
        if (response == JFileChooser.APPROVE_OPTION) {
            File file = new File(fileChooser.getSelectedFile().getAbsolutePath());
            try {
                FileReader fr = new FileReader(file);
                BufferedReader br = new BufferedReader(fr);
            
                DefaultTableModel model = (DefaultTableModel)jTable1.getModel();
                Object[] lines = br.lines().toArray();
                int lineght = lines.length;
                for (int i = 0; i < lineght; i++) {
                    String[] row = lines[i].toString().split(" ");
                    model.addRow(row);
                    jlresult.setText("Import complete");
                }
                // Get Row count from table
                int numrow = jTable1.getRowCount();
                for (int i = 0; i < numrow; i++){
                    String imtype = (String) jTable1.getValueAt(i, 3);
                    // Check If type is revenue to add value to array type revenue and if type is expeness will add to array type expeness
                    if (imtype.equals("revenue")){
                        String nameim = (String) jTable1.getValueAt(i, 0);
                        revenuename.add(nameim);
                            
                        String amountim = (String) jTable1.getValueAt(i, 1);
                        double amount = Double.parseDouble(amountim);
                        revenueamount.add(amount);
                            
                        String memoim = (String) jTable1.getValueAt(i, 2);
                        revenuememo.add(memoim);
                    } else if (imtype.equals("expeness")){ 
                        String nameim = (String) jTable1.getValueAt(i, 0);
                        expenessname.add(nameim);
                            
                        String amountim = (String) jTable1.getValueAt(i, 1);
                        double amount = Double.parseDouble(amountim);
                        expenessamount.add(amount);
                            
                        String memoim = (String) jTable1.getValueAt(i, 2);
                        expenessmemo.add(memoim);
                    }
                }
            } catch (FileNotFoundException ex) {
                Logger.getLogger(MenuUI.class.getName()).log(Level.SEVERE, null, ex);
            }
        /*
        Check If array is added correctly
        System.out.print(revenuename);
        System.out.print(revenueamount);
        System.out.print(revenuememo);
        System.out.print(expenessname);
        System.out.print(expenessamount);
        System.out.print(expenessmemo);
        */
        } else {
            JOptionPane.showMessageDialog(null, "Please check the path");
            jlresult.setText("Something is wrong?");
        }
    }//GEN-LAST:event_jbtnimportfileActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        System.exit(0);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        int index = jTable1.getSelectedRow();
        
        TableModel model = jTable1.getModel();
        
        String name = model.getValueAt(index, 0).toString();
        String amount = model.getValueAt(index, 1).toString();
        String memo = model.getValueAt(index, 2).toString();
        String type = model.getValueAt(index, 3).toString();
        
        shd.setVisible(true);
        shd.pack();
        shd.setLocationRelativeTo(null);
        shd.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        
        shd.shd_name.setText(name);
        shd.shd_amount.setText(amount);
        shd.shd_memo.setText(memo);
        shd.shd_type.setText(type);
    }//GEN-LAST:event_jTable1MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup btngroupRE;
    private javax.swing.ButtonGroup btngroupcal;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JButton jbtnadd;
    private javax.swing.JButton jbtncalculate;
    private javax.swing.JButton jbtnclear;
    private javax.swing.JButton jbtncleartable;
    private javax.swing.JButton jbtnimportfile;
    private javax.swing.JButton jbtnsavefile;
    private javax.swing.JLabel jlbal;
    private javax.swing.JLabel jlresult;
    private javax.swing.JRadioButton jrdep;
    private javax.swing.JRadioButton jrdexpeness;
    private javax.swing.JRadioButton jrdrevenue;
    private javax.swing.JRadioButton jrdrv;
    private javax.swing.JRadioButton jrdrvep;
    private javax.swing.JTextField jtfamount;
    private javax.swing.JTextField jtffilename;
    private javax.swing.JTextField jtfmemo;
    private javax.swing.JTextField jtfname;
    // End of variables declaration//GEN-END:variables
}
